package quotations

import (
	"bytes"
	"encoding/hex"
	"fmt"
	"math"
	"strings"
	"time"
)

type pdfCanvas struct {
	bytes.Buffer
}

func buildQuotationPDF(q Quotation) []byte {
	brand := parseBrandColor(q.NurseryBrandColor)
	var c pdfCanvas
	c.rectFill(50, 805, 495, 3, brand)
	c.text(50, 760, 22, true, pdfDark, textOr(q.NurseryName, "GreenRoot Quotation"))
	c.text(50, 741, 10, false, pdfMuted, textOr(q.NurseryPhone, ""))
	c.text(50, 724, 10, true, pdfDark, "Owner: "+textOr(q.CreatedByName, "-"))
	c.rectStroke(50, 704, 60, 17, brand)
	c.text(58, 709, 8, true, brand, quotationTypeLabel(q))

	c.text(395, 775, 9, true, pdfMuted, "QUOTATION")
	c.text(372, 748, 18, true, pdfDark, q.QuotationCode)
	c.meta(414, 725, "Date", formatPDFDateTime(q.CreatedAt))
	c.meta(384, 707, "Valid Until", validUntilText(q))
	c.line(50, 680, 545, 680, pdfBorder)

	if strings.EqualFold(q.QuotationType, "INTERNAL") {
		c.rectFill(50, 645, 495, 48, pdfSoftGreen)
		c.rectStroke(50, 645, 495, 48, brand)
		c.text(64, 674, 9, true, brand, "INTERNAL PLANNING DOCUMENT")
		c.text(64, 657, 9, false, pdfDark, "Not intended for external customer distribution.")
	} else {
		c.partyBox(50, 610, 220, "FROM", textOr(q.NurseryName, "-"), textOr(q.NurseryPhone, "-"), "Prepared by "+textOr(q.CreatedByName, "-"), brand)
		c.partyBox(295, 610, 250, "TO", textOr(q.RecipientName, "Customer details protected"), textOr(q.RecipientMobile, ""), "", pdfMuted)
	}

	tableY := 560.0
	if strings.EqualFold(q.QuotationType, "INTERNAL") {
		tableY = 585
	}
	tableBottom := c.itemsTable(q, tableY, brand)
	totalY := tableBottom - 52
	c.rectFill(50, totalY, 495, 44, pdfSoftGreen)
	c.rectStroke(50, totalY, 495, 44, brand)
	c.text(62, totalY+18, 13, true, brand, "GRAND TOTAL")
	c.text(430, totalY+22, 18, true, pdfDark, formatPDFMoney(q.TotalAmount))
	c.text(380, totalY+8, 8, false, pdfMuted, "("+amountInWords(q.TotalAmount)+")")

	nextY := totalY - 34
	if q.Notes != nil && strings.TrimSpace(*q.Notes) != "" {
		c.rectFill(50, nextY-34, 495, 42, pdfLight)
		c.rectStroke(50, nextY-34, 495, 42, pdfBorder)
		c.text(62, nextY-8, 8, true, pdfMuted, "NOTES")
		c.text(62, nextY-24, 9, false, pdfDark, truncatePDFText(strings.TrimSpace(*q.Notes), 88))
		nextY -= 54
	}

	c.rectFill(50, nextY-28, 495, 28, pdfAmberLight)
	c.rectStroke(50, nextY-28, 495, 28, pdfAmber)
	c.text(62, nextY-18, 8, true, pdfAmber, "!  Prices subject to availability. All prices are provided by the issuing nursery.")

	c.line(50, 72, 545, 72, pdfBorder)
	c.text(50, 52, 7, false, pdfMuted, "GreenRoot - Nursery Management Platform - Official quotation generated by API.")
	c.text(470, 52, 7, true, pdfMuted, "Page 1 of 1")

	return wrapPDF(c.String())
}

func (c *pdfCanvas) itemsTable(q Quotation, y float64, brand pdfColor) float64 {
	widths := []float64{28, 245, 58, 52, 62, 50}
	xs := []float64{50, 78, 323, 381, 433, 495}
	headers := []string{"#", "PLANT / ITEM", "SIZE", "QTY", "UNIT", "AMOUNT"}
	c.rectFill(50, y, 495, 25, brand)
	for i, h := range headers {
		c.text(xs[i]+6, y+9, 8, true, pdfWhite, h)
	}
	rowY := y - 28
	for i, item := range q.Items {
		rowH := 40.0
		if rowY < 105 {
			break
		}
		if i%2 == 0 {
			c.rectFill(50, rowY, 495, rowH, pdfWhite)
		} else {
			c.rectFill(50, rowY, 495, rowH, pdfLight)
		}
		c.rectStroke(50, rowY, 495, rowH, pdfBorder)
		for _, x := range xs[1:] {
			c.line(x, rowY, x, rowY+rowH, pdfBorder)
		}
		c.text(58, rowY+22, 9, false, pdfMuted, fmt.Sprintf("%d", i+1))
		c.text(86, rowY+23, 10, true, pdfDark, truncatePDFText(item.ScientificName, 34))
		if item.CommonName != nil {
			c.text(86, rowY+10, 8, false, pdfMuted, truncatePDFText(*item.CommonName, 34))
		}
		c.text(331, rowY+20, 9, false, pdfMuted, itemDescription(item))
		c.text(397, rowY+20, 10, false, pdfDark, formatPDFQty(item.Quantity))
		c.text(448, rowY+20, 10, false, pdfDark, formatPDFMoney(item.UnitPrice))
		c.text(504, rowY+20, 10, true, pdfDark, formatPDFMoney(item.TotalPrice))
		rowY -= rowH
	}
	_ = widths
	return rowY
}

func (c *pdfCanvas) partyBox(x, y, w float64, label, name, phone, foot string, labelColor pdfColor) {
	c.rectFill(x, y, w, 84, pdfLight)
	c.rectStroke(x, y, w, 84, pdfBorder)
	c.text(x+16, y+61, 9, true, labelColor, label)
	c.text(x+16, y+38, 13, true, pdfDark, truncatePDFText(name, 28))
	if phone != "" {
		c.text(x+16, y+22, 9, false, pdfMuted, phone)
	}
	if foot != "" {
		c.text(x+16, y+8, 8, false, pdfMuted, truncatePDFText(foot, 36))
	}
}

func (c *pdfCanvas) meta(x, y float64, label, value string) {
	c.text(x, y, 9, true, pdfMuted, label)
	c.text(x+58, y, 9, true, pdfDark, value)
}

func (c *pdfCanvas) text(x, y, size float64, bold bool, color pdfColor, text string) {
	if strings.TrimSpace(text) == "" {
		return
	}
	font := "F1"
	if bold {
		font = "F2"
	}
	c.setFill(color)
	fmt.Fprintf(c, "BT /%s %.1f Tf %.1f %.1f Td (%s) Tj ET\n", font, size, x, y, escapePDFText(toPDFASCII(text)))
}

func (c *pdfCanvas) rectFill(x, y, w, h float64, color pdfColor) {
	c.setFill(color)
	fmt.Fprintf(c, "%.1f %.1f %.1f %.1f re f\n", x, y, w, h)
}

func (c *pdfCanvas) rectStroke(x, y, w, h float64, color pdfColor) {
	c.setStroke(color)
	fmt.Fprintf(c, "%.1f %.1f %.1f %.1f re S\n", x, y, w, h)
}

func (c *pdfCanvas) line(x1, y1, x2, y2 float64, color pdfColor) {
	c.setStroke(color)
	fmt.Fprintf(c, "%.1f %.1f m %.1f %.1f l S\n", x1, y1, x2, y2)
}

func (c *pdfCanvas) setFill(color pdfColor) {
	fmt.Fprintf(c, "%.3f %.3f %.3f rg\n", color.r, color.g, color.b)
}

func (c *pdfCanvas) setStroke(color pdfColor) {
	fmt.Fprintf(c, "%.3f %.3f %.3f RG\n", color.r, color.g, color.b)
}

func wrapPDF(stream string) []byte {
	objects := []string{
		"<< /Type /Catalog /Pages 2 0 R >>",
		"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
		fmt.Sprintf("<< /Length %d >>\nstream\n%s\nendstream", len(stream), stream),
	}
	var out bytes.Buffer
	out.WriteString("%PDF-1.4\n")
	offsets := []int{0}
	for i, obj := range objects {
		offsets = append(offsets, out.Len())
		fmt.Fprintf(&out, "%d 0 obj\n%s\nendobj\n", i+1, obj)
	}
	xref := out.Len()
	fmt.Fprintf(&out, "xref\n0 %d\n0000000000 65535 f \n", len(objects)+1)
	for _, off := range offsets[1:] {
		fmt.Fprintf(&out, "%010d 00000 n \n", off)
	}
	fmt.Fprintf(&out, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objects)+1, xref)
	return out.Bytes()
}

type pdfColor struct{ r, g, b float64 }

var (
	pdfForest     = rgb(0x16, 0x65, 0x34)
	pdfDark       = rgb(0x1F, 0x29, 0x37)
	pdfMuted      = rgb(0x6B, 0x72, 0x80)
	pdfLight      = rgb(0xF8, 0xFA, 0xFC)
	pdfBorder     = rgb(0xE5, 0xE7, 0xEB)
	pdfSoftGreen  = rgb(0xF0, 0xFF, 0xF4)
	pdfAmber      = rgb(0xD9, 0x77, 0x06)
	pdfAmberLight = rgb(0xFE, 0xF3, 0xC7)
	pdfWhite      = rgb(0xFF, 0xFF, 0xFF)
)

func rgb(r, g, b int) pdfColor {
	return pdfColor{float64(r) / 255, float64(g) / 255, float64(b) / 255}
}

// parseBrandColor converts a CSS hex color (#RRGGBB) to a pdfColor.
// Falls back to pdfForest if nil, empty, or malformed.
func parseBrandColor(s *string) pdfColor {
	if s == nil || len(*s) == 0 {
		return pdfForest
	}
	clean := strings.TrimPrefix(*s, "#")
	if len(clean) != 6 {
		return pdfForest
	}
	b, err := hex.DecodeString(clean)
	if err != nil || len(b) != 3 {
		return pdfForest
	}
	return rgb(int(b[0]), int(b[1]), int(b[2]))
}

func quotationTypeLabel(q Quotation) string {
	if strings.EqualFold(q.QuotationType, "INTERNAL") {
		return "INTERNAL"
	}
	return "QUOTATION"
}

func validUntilText(q Quotation) string {
	if q.ValidUntil != nil {
		return q.ValidUntil.Local().Format("02 Jan 2006")
	}
	return q.CreatedAt.Local().Add(15 * 24 * time.Hour).Format("02 Jan 2006")
}

func itemDescription(item QuotationItem) string {
	if item.Description == nil || strings.TrimSpace(*item.Description) == "" {
		return "-"
	}
	return truncatePDFText(strings.TrimSpace(*item.Description), 10)
}

func escapePDFText(text string) string {
	text = strings.ReplaceAll(text, `\`, `\\`)
	text = strings.ReplaceAll(text, "(", `\(`)
	text = strings.ReplaceAll(text, ")", `\)`)
	return text
}

func toPDFASCII(text string) string {
	replacer := strings.NewReplacer("₹", "Rs.", "—", "-", "–", "-", "·", "-", "“", `"`, "”", `"`)
	text = replacer.Replace(text)
	var b strings.Builder
	for _, r := range text {
		if r >= 32 && r <= 126 {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func formatPDFMoney(amount float64) string {
	return fmt.Sprintf("Rs.%.2f", amount)
}

func formatPDFQty(qty float64) string {
	if qty == math.Trunc(qty) {
		return fmt.Sprintf("%.0f", qty)
	}
	return fmt.Sprintf("%.2f", qty)
}

func formatPDFDateTime(t time.Time) string {
	return t.Local().Format("02 Jan 2006, 03:04 pm")
}

func truncatePDFText(text string, max int) string {
	if len(text) <= max {
		return text
	}
	if max <= 3 {
		return text[:max]
	}
	return text[:max-3] + "..."
}

func textOr(value *string, fallback string) string {
	if value == nil || strings.TrimSpace(*value) == "" {
		return fallback
	}
	return strings.TrimSpace(*value)
}

func amountInWords(amount float64) string {
	totalPaise := int(math.Round(amount * 100))
	rupees := totalPaise / 100
	paise := totalPaise % 100
	if rupees == 0 && paise == 0 {
		return "Zero Rupees Only"
	}
	parts := make([]string, 0, 2)
	if rupees > 0 {
		parts = append(parts, numberToWords(rupees)+" Rupees")
	}
	if paise > 0 {
		parts = append(parts, numberToWords(paise)+" Paise")
	}
	return strings.Join(parts, " and ") + " Only"
}

func numberToWords(n int) string {
	if n == 0 {
		return "Zero"
	}
	ones := []string{"", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"}
	tens := []string{"", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"}
	parts := make([]string, 0)
	scales := []struct {
		value int
		name  string
	}{{10000000, "Crore"}, {100000, "Lakh"}, {1000, "Thousand"}}
	for _, scale := range scales {
		if n >= scale.value {
			parts = append(parts, numberToWords(n/scale.value)+" "+scale.name)
			n %= scale.value
		}
	}
	if n >= 100 {
		parts = append(parts, ones[n/100]+" Hundred")
		n %= 100
	}
	if n >= 20 {
		parts = append(parts, tens[n/10])
		n %= 10
	}
	if n > 0 {
		parts = append(parts, ones[n])
	}
	return strings.Join(parts, " ")
}
